#:schema https://raw.githubusercontent.com/rugix/rugix/refs/v0.8/schemas/rugix-ctrl-system.schema.json
[config-partition]
partition = 1
protected = true

[data-partition]
partition = 4

[boot-flow]
type = "uboot"

[boot-groups.a]
slots = { system = "system-a" }

[boot-groups.b]
slots = { system = "system-b" }

[slots.system-a]
type = "block"
partition = 2
immutable = true

[slots.system-b]
type = "block"
partition = 3
immutable = true
